import { Recipe } from './recipe';

export const RECIPES : Recipe[] = [
    {
        name : 'Spaghetti rode saus',
        description : 'pasta/pastasaus/ui/knoflook/prei/wortel/selderij/paprika/geraspte kaas',
        category : 'Pasta',
        vegan : true,
        quick : false
    },
    {
        name : 'Pastasalade',
        description : 'pasta/avocado/ijsbergsla/paprika/pesto/mozzarella/cherrytomaatjes/(spekjes)',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Roerbakgroente met rijst',
        description : 'rijst/ui/knoflook/paprika/prei/taugé/wortel/nep-kip',
        category : 'Rijst',
        vegan : true,
        quick : true,
    },
    {
        name : 'Chili',
        description : '',
        category : 'Overig',
        vegan : true,
        quick : false,
    },
    {
        name : 'Couscoussalade',
        description : 'Couscous/paprika/courgette/tomaatjes/(gerookte kip)',
        category : 'Overig',
        vegan : true,
        quick : false,
    },
    {
        name : 'Aardappel, burger en rauwkost',
        description : '',
        category : 'Aardappel',
        vegan : true,
        quick : false,
    },
    {
        name : 'Rijstbowl',
        description : '',
        category : 'Rijst',
        vegan : true,
        quick : true,
    },
    {
        name : 'Lasagne',
        description : '',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Fancy lasagne',
        description : '',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Soep met stokbrood en rauwkost',
        description : '',
        category : 'Overig',
        vegan : true,
        quick : true,
    },
    {
        name : 'Nasi',
        description : '',
        category : 'Rijst',
        vegan : true,
        quick : false,
    },
    {
        name : 'Eenpans aardappel met groente',
        description : '',
        category : 'Aardappel',
        vegan : true,
        quick : false,
    },
    {
        name : 'Macaroni schotel',
        description : '',
        category : 'Pasta',
        vegan : false,
        quick : false,
    },
    {
        name : 'Stoofpot',
        description : '',
        category : 'Overig',
        vegan : false,
        quick : false,
    },
    {
        name : 'Stamppot',
        description : '',
        category : 'Aardappel',
        vegan : false,
        quick : false,
    },
    {
        name : 'Curry (ew)',
        description : '',
        category : 'Rijst',
        vegan : false,
        quick : false,
    },
    {
        name : 'Pasta Vae soli',
        description : '',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Pasta pesto à la Loes',
        description : '',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Pasta spinazie à la Loes',
        description : '',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Roerbak broccoli',
        description : '',
        category : 'Overig',
        vegan : true,
        quick : true,
    },
    {
        name : 'Wraps',
        description : '',
        category : 'Overig',
        vegan : false,
        quick : false,
    },
    {
        name : 'Zalm in sojasaus',
        description : '',
        category : 'Overig',
        vegan : false,
        quick : false,
    }
]
