import { Recipe } from './recipe';

export const RECIPES : Recipe[] = [
    {
        name : 'Spaghetti rode saus',
        description : 'pasta/pastasaus/ui/knoflook/prei/wortel/selderij/paprika/geraspte kaas',
        category : 'Pasta',
        vegan : true,
        quick : false
    },
    {
        name : 'Pastasalade',
        description : 'pasta/avocado/ijsbergsla/paprika/pesto/mozzarella/cherrytomaatjes/(spekjes)',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Roerbakgroente met rijst',
        description : 'rijst/ui/knoflook/paprika/prei/taugé/wortel/nep-kip',
        category : 'Rijst',
        vegan : true,
        quick : true,
    },
    {
        name : 'Chili',
        description : 'Kidney bonen/bruine bonen/chili bonen/mais/ananasstukjes',
        category : 'Overig',
        vegan : true,
        quick : false,
    },
    {
        name : 'Couscoussalade',
        description : 'Couscous/paprika/courgette/tomaatjes/(gerookte kip)',
        category : 'Overig',
        vegan : true,
        quick : false,
    },
    {
        name : 'Aardappel, burger en rauwkost',
        description : 'Aardappel/(vega) burger/paprika/komkommer/wortel',
        category : 'Aardappel',
        vegan : true,
        quick : false,
    },
    {
        name : 'Rijstbowl',
        description : 'Lime and coriander rice/falafel/avocado/paprika/komkommer/zoete aardappel',
        category : 'Rijst',
        vegan : true,
        quick : true,
    },
    {
        name : 'Lasagne',
        description : '',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Fancy lasagne',
        description : '',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Soep met stokbrood en rauwkost',
        description : '(Kippen)bouillon/stokbrood/paprika/wortel/komkommer',
        category : 'Overig',
        vegan : true,
        quick : true,
    },
    {
        name : 'Nasi',
        description : 'Rijst/prei/wortel/paprika/nasi boemboe/nepkip',
        category : 'Rijst',
        vegan : true,
        quick : false,
    },
    {
        name : 'Eenpans aardappel met groente',
        description : 'Aardappels/thijm/paprika/tomaat/prei',
        category : 'Aardappel',
        vegan : true,
        quick : false,
    },
    {
        name : 'Macaroni schotel',
        description : 'Macaroni/hamblokjes/spekjes/ei',
        category : 'Pasta',
        vegan : false,
        quick : false,
    },
    {
        name : 'Stoofpot',
        description : '',
        category : 'Overig',
        vegan : false,
        quick : false,
    },
    {
        name : 'Stamppot',
        description : 'Aardappel/andijvie/spekjes',
        category : 'Aardappel',
        vegan : false,
        quick : false,
    },
    {
        name : 'Curry (ew)',
        description : '',
        category : 'Rijst',
        vegan : true,
        quick : false,
    },
    {
        name : 'Pasta Vae soli',
        description : 'Pasta/ui/knoflook/spinazie a la creme/champignons/zwarte olijven/(spekjes)',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Pasta pesto à la Loes',
        description : 'Pasta/knoflook/gedroogde tomaten/champignons/pesto/creme fraiche/zwarte olijven',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Pasta spinazie à la Loes',
        description : '',
        category : 'Pasta',
        vegan : true,
        quick : false,
    },
    {
        name : 'Roerbak broccoli',
        description : '',
        category : 'Overig',
        vegan : true,
        quick : true,
    },
    {
        name : 'Wraps',
        description : 'Wraps/mexicaanse groente/sla/creme fraiche/geraspte kaas',
        category : 'Overig',
        vegan : false,
        quick : false,
    },
    {
        name : 'Zalm in sojasaus',
        description : 'Zalm/sojasau/groente/aardappel of rijst',
        category : 'Overig',
        vegan : false,
        quick : false,
    }
]
